--
-- PostgreSQL database dump
--

\restrict yI7kKtfscK4cksJLwEANaoYlWIfjSBTAxriN6GQsd7lUzk1Xc3ZHv7TnULsKJbm

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assets (
    id bigint NOT NULL,
    cost numeric(38,2) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    type character varying(255),
    CONSTRAINT assets_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'LEASED'::character varying])::text[])))
);


ALTER TABLE public.assets OWNER TO postgres;

--
-- Name: assets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    full_name character varying(255) NOT NULL,
    organization character varying(255),
    phone character varying(255) NOT NULL
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contracts (
    id bigint NOT NULL,
    end_date date NOT NULL,
    amount numeric(38,2) NOT NULL,
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    asset_id bigint NOT NULL,
    client_id bigint NOT NULL,
    CONSTRAINT contracts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CLOSED'::character varying])::text[])))
);


ALTER TABLE public.contracts OWNER TO postgres;

--
-- Name: contracts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contracts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.news (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    image_url character varying(255),
    title character varying(255) NOT NULL
);


ALTER TABLE public.news OWNER TO postgres;

--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    payment_date date NOT NULL,
    status character varying(255) NOT NULL,
    contract_id bigint NOT NULL,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PAID'::character varying, 'PENDING'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message text,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    processed boolean NOT NULL
);


ALTER TABLE public.requests OWNER TO postgres;

--
-- Name: requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: assets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assets (id, cost, name, status, type) FROM stdin;
1	4200000.00	Электромобиль Tesla Model 3	AVAILABLE	Легковой электромобиль
2	8900000.00	Экскаватор JCB 3CX	AVAILABLE	Строительная техника
3	6300000.00	Грузовик MAN TGL 12.220	AVAILABLE	Грузовой автомобиль
\.


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clients (id, created_at, email, full_name, organization, phone) FROM stdin;
1	2025-11-15 21:13:04.924936	info@technomarket.ru	ТехноМаркет	ООО «ТехноМаркет»	+7 (495) 555-12-34
2	2025-11-15 21:13:26.220306	sergeev.mp@mail.ru	Сергеев Максим Павлович	ИП Сергеев Максим Павлович	+7 (921) 818-44-11
3	2025-11-15 21:13:55.318982	office@stroytech.ru	СтройТех Сервис	ООО «СтройТех Сервис»	+7 (812) 300-77-55
\.


--
-- Data for Name: contracts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contracts (id, end_date, amount, start_date, status, asset_id, client_id) FROM stdin;
1	2027-12-01	3345000.00	2025-12-01	ACTIVE	1	1
2	2027-01-18	2530000.00	2025-12-18	ACTIVE	2	3
3	2025-11-02	7115000.00	2025-02-02	CLOSED	3	2
\.


--
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.news (id, content, created_at, image_url, title) FROM stdin;
1	Правительство расширило программу субсидирования лизинга на электромобили. Теперь предприниматели могут получить компенсацию до 25% от стоимости автомобиля, а также воспользоваться сниженной ставкой по договору.\r\nНаша компания предлагает широкий выбор электрокаров — от компактных моделей для курьерской доставки до премиальных бизнес-седанов. Все автомобили включают расширенную гарантию и полное сервисное обслуживание.\r\nУсловия акции действуют до конца года.\r\n	2025-11-15 21:08:32.786782	https://plus.unsplash.com/premium_photo-1714672716183-c717a99f857f?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D	Лизинг электромобилей теперь доступен для малого и среднего бизнеса
2	В связи с ростом количества клиентов в Северо-Западном регионе мы открываем новый офис на Сенном рынке. Теперь заключить договор лизинга, подать документы и получить консультацию можно лично, без предварительной записи.\r\nОфис работает ежедневно с 09:00 до 20:00. В ближайшие месяцы также планируется открытие сервисной зоны и точки выдачи автомобилей.\r\nБудем рады видеть вас!	2025-11-15 21:10:13.141186	https://images.unsplash.com/photo-1603955129944-7f2dbff89b04?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D	Мы открываем новый офис на Сенном рынке в Санкт-Петербурге
3	Компания обновила тарифы на лизинг строительной и промышленной техники. Для клиентов доступна ставка от 6,9% годовых при авансе от 10%.\r\nВ программу входят экскаваторы, погрузчики, буровые установки, а также дорожная техника ведущих производителей. Доступно ускоренное оформление — договор можно получить в течение одного рабочего дня.\r\nАкция действует до 30 апреля.	2025-11-15 21:11:27.098685	https://images.unsplash.com/photo-1523848309072-c199db53f137?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D	Снижение ставок на спецтехнику — теперь от 6,9% годовых
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payments (id, amount, payment_date, status, contract_id) FROM stdin;
1	145000.00	2025-12-01	PAID	1
2	230000.00	2025-12-18	PAID	2
3	115000.00	2025-02-02	PAID	3
\.


--
-- Data for Name: requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.requests (id, created_at, message, name, phone, processed) FROM stdin;
1	2025-11-15 21:19:06.317426	Рассматриваю лизинг электромобиля для доставки заказов.	Ирина	+7 (926) 533-21-88	f
3	2025-11-15 21:19:44.22426	Нужна спецтехника для строительной площадки. Нужно 2 экскаватора.	Анна	+7 (904) 123-45-44	t
2	2025-11-15 21:19:25.506584	Интересует лизинг грузовика на 12 месяцев.	Дмитрий	+7 (901) 722-90-11	t
4	2025-11-15 21:32:32.271659	ТЕСТ	Иван	+79998882244	t
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, role, username) FROM stdin;
1	$2a$10$bJOW.hJlAQHSYJXBPE7BqOJq0tgSZqeHQSirbuEPlX1FTJkfDkPC6	ADMIN	admin
2	$2a$10$jDinHQf7oHB3kdEGXe9ha.7OOUfDKOWar8Vleyyj9lGZXbwBwvjWK	MANAGER	manager
\.


--
-- Name: assets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assets_id_seq', 3, true);


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clients_id_seq', 3, true);


--
-- Name: contracts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contracts_id_seq', 3, true);


--
-- Name: news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.news_id_seq', 3, true);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_id_seq', 3, true);


--
-- Name: requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.requests_id_seq', 4, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: assets assets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: contracts contracts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT contracts_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: contracts fkjvom059ywi0sl9cde5cog6waa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT fkjvom059ywi0sl9cde5cog6waa FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- Name: payments fkqywegtqyijw241foqfkseq1l6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkqywegtqyijw241foqfkseq1l6 FOREIGN KEY (contract_id) REFERENCES public.contracts(id);


--
-- Name: contracts fkrqssit79jdlx2ch8ubajt6w4y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT fkrqssit79jdlx2ch8ubajt6w4y FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- PostgreSQL database dump complete
--

\unrestrict yI7kKtfscK4cksJLwEANaoYlWIfjSBTAxriN6GQsd7lUzk1Xc3ZHv7TnULsKJbm

